### ISSUE TITLE
Batching requests

### ISSUE THREAD

**Issue by alexkahn** [django-haystack/celery-haystack#54]
In the Haystack [docs](http://django-haystack.readthedocs.org/en/v2.4.1/best_practices.html#use-of-a-queue-for-a-better-user-experience) there is a strategy for updates that uses a queue to batch the requests to the engine.

In the case of elasticsearch, it's HTTP server isn't as great as it's bulk processor (I'm sure that others have similar HTTP limitations) so it seems like a good use case to implement a way for a user to submit some kind of logic to the task enqueuer so that requests can be batched at the expense of immediacy. In the base base (i.e. no user supplied logic) to do a 'wait a couple seconds' before putting all this together. Not really sure what the exact implications on server memory or the like but I keep hitting concurrency bounds with elasticsearch.

Happy to work with the team on getting this out.

**Comment by stefanw** [comment]
`celery-haystack` implements a `QueuedSignalProcessor` as seen in the `haystack` docs: this package sole purpose is to implement that queueing strategy using `celery` tasks.

However, the single haystack object updates get queued into individual tasks and are not batched together. I'm not sure how this batching should work in the current architecture, because right now every update gets one task that runs individually and the queue's execution is left up to celery.

Implementing batch/bulk indexing for specific search engines is not in the scope of this package. If you're running into performance problems because of high frequency updates, you might need to come up with a custom solution.

If you have an idea how to make this work, please feel free to reopen.

**Comment by yeago** [comment]
somewhat related http://docs.celeryproject.org/en/latest/reference/celery.contrib.batches.html
